# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 159b64f64681648004f7cdc695b0ef5a2106dafce39d52e01c581890db12636e52c82aeb883b7810a0b9da5d221bdcd94fef5484a7f739e5abae7348c58047ed

test:
  secret_key_base: e3ec54fdc4b40b349d667f85c3e5f545c03300d487b053cdaf48a3bf5c5c37d6d74003a3d76e58a27b2813cc9d66c37be3eff37a62a753793c6857c86c74ff12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
